package eventmanagementsystem;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author joelb
 */
public class Registerform extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    int reg;
    String selected, eventname,  eventvenue;
    Date eventdate;
    public Registerform(int regno) {
        reg = regno;
        initComponents();
        Displaylistedevents();
        Displayregisteredevents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listedcombobox = new javax.swing.JComboBox<>();
        Register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        regeventstable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 217, 217));
        setPreferredSize(new java.awt.Dimension(1105, 786));
        setSize(new java.awt.Dimension(1105, 786));

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setPreferredSize(new java.awt.Dimension(1105, 122));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(217, 217, 217));
        jLabel3.setText("Welcome Student");
        jLabel3.setAlignmentX(1057.0F);
        jLabel3.setAlignmentY(27.0F);
        jLabel3.setPreferredSize(new java.awt.Dimension(319, 53));

        Logout.setBackground(new java.awt.Color(23, 23, 23));
        Logout.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(217, 217, 217));
        Logout.setText("Log Out");
        Logout.setAlignmentX(1291.0F);
        Logout.setAlignmentY(105.0F);
        Logout.setBorder(null);
        Logout.setPreferredSize(new java.awt.Dimension(85, 33));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(23, 23, 23));
        Back.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(217, 217, 217));
        Back.setText("<-  Back");
        Back.setBorder(null);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setPreferredSize(new java.awt.Dimension(1105, 664));

        jLabel1.setBackground(new java.awt.Color(217, 217, 217));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("Listed Events");
        jLabel1.setPreferredSize(new java.awt.Dimension(117, 25));

        listedcombobox.setBackground(new java.awt.Color(194, 194, 194));
        listedcombobox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        listedcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        listedcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listedcomboboxActionPerformed(evt);
            }
        });

        Register.setBackground(new java.awt.Color(23, 23, 23));
        Register.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        Register.setForeground(new java.awt.Color(217, 217, 217));
        Register.setText("Register");
        Register.setBorder(null);
        Register.setPreferredSize(new java.awt.Dimension(146, 46));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(217, 217, 217));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setText("Register Events");
        jLabel2.setPreferredSize(new java.awt.Dimension(117, 25));

        regeventstable.setBackground(new java.awt.Color(194, 194, 194));
        regeventstable.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        regeventstable.setForeground(new java.awt.Color(23, 23, 23));
        regeventstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Event Name", "Event Date", "Venue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        regeventstable.setRowHeight(30);
        jScrollPane1.setViewportView(regeventstable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(listedcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listedcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Displaylistedevents(){
    String b[]=new String[200];
    int i=0;
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagenetsystem","root","2511" );
            Statement stmt=con.createStatement();
            
            PreparedStatement preparedStatement = con.prepareStatement("SELECT eventname FROM listedevents");
            preparedStatement.executeQuery();  
            ResultSet rs= preparedStatement.executeQuery();
            while(rs.next()){
                b[i]=rs.getString(1);
                listedcombobox.addItem(b[i]);
                i++;
            }

            
        }catch(Exception e){
            
        }
    }


 void Displayregisteredevents(){
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagenetsystem","root","2511" );
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery("select eventname, eventdate, venue from registeredevents where stuid=" + reg);
            regeventstable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
        }
    }

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed

        OpenStudentDashboard(reg);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void listedcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listedcomboboxActionPerformed
        
        
    }//GEN-LAST:event_listedcomboboxActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        OpenLogin();
        
    }//GEN-LAST:event_LogoutActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        selected = (String) listedcombobox.getSelectedItem();
        getevent();
        addevent();
        listedcombobox.setSelectedIndex(-1);
        JOptionPane.showMessageDialog(null,"Event Added Successfully");
        
        
    }//GEN-LAST:event_RegisterActionPerformed
 
    
    void OpenLogin(){
     Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        dispose();
    }
    void OpenStudentDashboard(int reg){
        StudentDashboard dash = new StudentDashboard(reg);
        dash.setVisible(true);
        dash.pack();
        dash.setLocationRelativeTo(null);
    }
    
     void addevent() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagenetsystem", "root", "2511");
            PreparedStatement preparedStatement = con.prepareStatement("insert into registeredevents(stuid, eventname, eventdate, venue) values (?, ?, ?, ?)");
            preparedStatement.setInt(1, reg);
            preparedStatement.setString(2, eventname);
            preparedStatement.setDate(3, eventdate);
            preparedStatement.setString(4, eventvenue);
            int row = preparedStatement.executeUpdate();
            Displayregisteredevents();
          
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    void getevent() {
        try {
            String a[] = new String[100];
            Date b[] = new Date[100];
            String c[] = new String[100];
            int i = 0;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagenetsystem", "root", "2511");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select eventname, eventdate, venue from listedevents");

            while (rs.next()) {
                a[i] = rs.getString(1);
                b[i] = rs.getDate(2);
                c[i] = rs.getString(3);
                i++;
            }

            for (int j = 0; j < i; j++) {
                if (a[j].equals(selected)) {
                    eventname = a[j];
                    eventdate = b[j];
                    eventvenue = c[j];
                }
            }
            System.out.print("Name : " + eventname + " Date : " + eventdate + " Venue : " + eventvenue);

        } catch (Exception e) {
            System.out.println("Exception");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Registerform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listedcombobox;
    private javax.swing.JTable regeventstable;
    // End of variables declaration//GEN-END:variables
}
